const ArchitecturesPictures = [
    { name: 'Chemins A', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696053/Portfolio%20Maxime%20Turpault/Architectures/Chemins.a_dq5ex6.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656697148/Portfolio%20Maxime%20Turpault/Architectures/Miniatures/Chemins.a_dmj20x.jpg' },
    { name: 'Chemins B', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696053/Portfolio%20Maxime%20Turpault/Architectures/Chemins.b_lzmvvg.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656697148/Portfolio%20Maxime%20Turpault/Architectures/Miniatures/Chemins.b_ebg0xv.jpg' },
    { name: 'Chemins C', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696053/Portfolio%20Maxime%20Turpault/Architectures/Chemins.c_xvzfbg.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656697148/Portfolio%20Maxime%20Turpault/Architectures/Miniatures/Chemins.c_pkcexc.jpg' },
    { name: 'Chemins D', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696053/Portfolio%20Maxime%20Turpault/Architectures/Chemins.d_wykbmh.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656697148/Portfolio%20Maxime%20Turpault/Architectures/Miniatures/Chemins.d_wejwpw.jpg' },
    { name: 'Chemins E', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696053/Portfolio%20Maxime%20Turpault/Architectures/Chemins.e_vj2o12.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656697148/Portfolio%20Maxime%20Turpault/Architectures/Miniatures/Chemins.e_gjizrw.jpg' },
    { name: 'Chemins F', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696053/Portfolio%20Maxime%20Turpault/Architectures/Chemins.f_j0tfki.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656697148/Portfolio%20Maxime%20Turpault/Architectures/Miniatures/Chemins.f_iuvyej.jpg' },
    { name: 'Chemins G', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696054/Portfolio%20Maxime%20Turpault/Architectures/Chemins.g_watsh7.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656697148/Portfolio%20Maxime%20Turpault/Architectures/Miniatures/Chemins.g_hui73p.jpg' },
    { name: 'La Défense A', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696054/Portfolio%20Maxime%20Turpault/Architectures/La_D%C3%A9fense.a_lhrtqz.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656697148/Portfolio%20Maxime%20Turpault/Architectures/Miniatures/La_D%C3%A9fense.a_eocwn5.jpg' },
    { name: 'La Défense B', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696054/Portfolio%20Maxime%20Turpault/Architectures/La_D%C3%A9fense.b_rm17sj.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656697148/Portfolio%20Maxime%20Turpault/Architectures/Miniatures/La_D%C3%A9fense.b_yxdt7m.jpg' },
    { name: 'La Défense C', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696054/Portfolio%20Maxime%20Turpault/Architectures/La_D%C3%A9fense.c_o2ybrh.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656697148/Portfolio%20Maxime%20Turpault/Architectures/Miniatures/La_D%C3%A9fense.c_tkj9wm.jpg' },
    { name: 'La Défense D', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696055/Portfolio%20Maxime%20Turpault/Architectures/La_D%C3%A9fense.d_w07sk5.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656697148/Portfolio%20Maxime%20Turpault/Architectures/Miniatures/La_D%C3%A9fense.d_eyv1zq.jpg' },
    { name: 'La Défense E', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696055/Portfolio%20Maxime%20Turpault/Architectures/La_D%C3%A9fense.e_kry1t6.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656697149/Portfolio%20Maxime%20Turpault/Architectures/Miniatures/La_D%C3%A9fense.e_hfta4m.jpg' },
]

export default ArchitecturesPictures;