const PortraitsPictures = [
    { name: 'Silhouette A', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696128/Portfolio%20Maxime%20Turpault/Portraits/Silhouette.a_epx6gt.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696981/Portfolio%20Maxime%20Turpault/Portraits/Miniatures/Silhouette.a_ul7m0o.jpg' },
    { name: 'Silhouette B', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696128/Portfolio%20Maxime%20Turpault/Portraits/Silhouette.b_j0zrtl.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696981/Portfolio%20Maxime%20Turpault/Portraits/Miniatures/Silhouette.b_d9fo3x.jpg' },
    { name: 'Silhouette C', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696128/Portfolio%20Maxime%20Turpault/Portraits/Silhouette.c_ft6bca.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696981/Portfolio%20Maxime%20Turpault/Portraits/Miniatures/Silhouette.c_zucr32.jpg' },
    { name: 'Surveillant A', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696129/Portfolio%20Maxime%20Turpault/Portraits/Surveillant.a_je6q4q.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696981/Portfolio%20Maxime%20Turpault/Portraits/Miniatures/Surveillant.a_kwjiui.jpg' },
    { name: 'Surveillant B', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696129/Portfolio%20Maxime%20Turpault/Portraits/Surveillant.b_j398hx.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696981/Portfolio%20Maxime%20Turpault/Portraits/Miniatures/Surveillant.c_lgk9bg.jpg' },
    { name: 'Surveillant C', img: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696129/Portfolio%20Maxime%20Turpault/Portraits/Surveillant.c_amuqww.jpg', miniatures: 'https://res.cloudinary.com/dktfcexev/image/upload/v1656696981/Portfolio%20Maxime%20Turpault/Portraits/Miniatures/Surveillant.b_zgrhfv.jpg' },
]

export default PortraitsPictures;